# Generated by Django 4.0.3 on 2022-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTransAPI', '0003_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='transactions',
            name='type_trans',
            field=models.SmallIntegerField(default=0),
        ),
    ]
