# Generated by Django 4.0.3 on 2022-04-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserTransAPI', '0005_alter_transactions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
