# Generated by Django 4.0.3 on 2022-04-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserTransAPI', '0008_rename_type_trans_transactions_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
